name: cubit_auth
description: Authorization with cubit sample app.

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #state management
  flutter_bloc: ^8.1.1
  hydrated_bloc: ^9.0.0

  #form
  mask_text_input_formatter: ^2.0.0
  form_field_validator: ^1.1.0

  #ui
  cupertino_icons: ^1.0.3
  fluttertoast: ^8.0.7

  #file location
  path_provider: ^2.0.2

  #domain
  freezed: ^2.2.1
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  equatable: ^2.0.3

  #di
  get_it: ^7.1.4

  #local db
  shared_preferences: ^2.0.6


dev_dependencies:
  build_runner: ^2.0.5
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true

